name: AI Inference

on:
  workflow_dispatch

permissions:
  contents: read
  models: read
  
jobs:
  inference:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - uses: actions/ai-inference@v1
       continue-on-error: true
       with:
         prompt: 'EE!'
         enable-github-mcp: true
         token: ${{ github.token }}
         github-mcp-token: ${{ secrets.MCP_TOKEN }}

     - uses: actions/ai-inference@v1
       continue-on-error: true
       with:
        prompt: 'EE!'
        model: 'gpt-4-turbo'  # or another model with larger context
        enable-github-mcp: true
        token: ${{ github.token }}
        github-mcp-token: ${{ secrets.MCP_TOKEN }}

     - uses: actions/ai-inference@v1
       with:
        prompt: 'Analyze only the main README.md file'
        enable-github-mcp: true
        token: ${{ github.token }}
        github-mcp-token: ${{ secrets.MCP_TOKEN }}
     
     
   
   
